<#
.SYNOPSIS
    Documents all Parallels RAS installation settings to a Word document using PSWriteWord.

.DESCRIPTION
    This script collects all configuration settings from a Parallels RAS installation
    using the Parallels RAS PowerShell module and exports them to a Word document.
    Uses PSWriteWord module which does not require Microsoft Word to be installed.

.PARAMETER OutputPath
    Path where the Word document will be saved. Defaults to current directory.

.PARAMETER DocumentName
    Name of the Word document (without extension). Defaults to "RAS-Settings-{timestamp}".

.EXAMPLE
    .\Export-RASSettings-PSWriteWord.ps1 -OutputPath "C:\Reports" -DocumentName "RAS-Configuration"

.NOTES
    Requires:
    - Parallels RAS PowerShell module (rasadmin)
    - PSWriteWord module (Install-Module PSWriteWord)
    - Appropriate permissions to access RAS configuration
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory = $false)]
    [string]$OutputPath = (Get-Location).Path,
    
    [Parameter(Mandatory = $false)]
    [string]$DocumentName = "RAS-Settings-$(Get-Date -Format 'yyyyMMdd-HHmmss')"
)

# Error handling
$ErrorActionPreference = "Continue"

# Disable all confirmation prompts and make script fully non-interactive
$ConfirmPreference = "None"
$WhatIfPreference = $false
$ProgressPreference = "SilentlyContinue"
$VerbosePreference = "SilentlyContinue"
$DebugPreference = "SilentlyContinue"
$WarningPreference = "Continue"

# Helper function to convert objects to array of hashtables for table display
function ConvertTo-HashtableArray {
    param([Parameter(ValueFromPipeline)]$InputObject)
    
    begin { $array = @() }
    process {
        $hashtable = @{}
        foreach ($prop in $InputObject.PSObject.Properties) {
            $value = $prop.Value
            if ($value -is [array]) {
                $value = ($value -join ", ")
            } elseif ($null -eq $value) {
                $value = ""
            }
            $hashtable[$prop.Name] = [string]$value
        }
        $array += [PSCustomObject]$hashtable
    }
    end { return $array }
}

# Function to write log messages
function Write-LogMessage {
    param([string]$Message, [string]$Level = "INFO")
    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    Write-Host "[$timestamp] [$Level] $Message" -ForegroundColor $(if ($Level -eq "ERROR") { "Red" } elseif ($Level -eq "WARNING") { "Yellow" } else { "Green" })
}

# Check if Parallels RAS module is installed
Write-LogMessage "Checking for Parallels RAS PowerShell module..."
try {
    $rasModule = Get-Module -ListAvailable -Name "rasadmin" | Select-Object -First 1
    if (-not $rasModule) {
        throw "Parallels RAS PowerShell module not found. Please install it first."
    }
    Write-LogMessage "Found Parallels RAS module version $($rasModule.Version)"
    
    # Import the module
    Import-Module -Name "rasadmin" -ErrorAction Stop
    Write-LogMessage "Module imported successfully"
} catch {
    Write-LogMessage "Error loading Parallels RAS module: $_" "ERROR"
    exit 1
}

# Check for PSWriteWord module
Write-LogMessage "Checking for PSWriteWord module..."
try {
    $psWriteWordModule = Get-Module -ListAvailable -Name "PSWriteWord" | Select-Object -First 1
    if (-not $psWriteWordModule) {
        Write-LogMessage "PSWriteWord module not found. Installing..." "WARNING"
        Install-Module -Name PSWriteWord -Scope CurrentUser -Force -SkipPublisherCheck -Confirm:$false -AllowClobber
        Write-LogMessage "PSWriteWord module installed successfully"
    }
    Import-Module -Name PSWriteWord -ErrorAction Stop
    Write-LogMessage "PSWriteWord module loaded successfully"
} catch {
    Write-LogMessage "Error loading PSWriteWord module: $_" "ERROR"
    Write-LogMessage "Please install it with: Install-Module -Name PSWriteWord -Scope CurrentUser" "ERROR"
    exit 1
}

# Ensure output directory exists
if (-not (Test-Path $OutputPath)) {
    Write-LogMessage "Creating output directory: $OutputPath"
    try {
        New-Item -ItemType Directory -Path $OutputPath -Force | Out-Null
    } catch {
        Write-LogMessage "Error creating output directory: $_" "ERROR"
        exit 1
    }
}

# Create Word document
$fullPath = Join-Path $OutputPath "$DocumentName.docx"
Write-LogMessage "Creating Word document at: $fullPath"

try {
    # Create new Word document
    $WordDocument = New-WordDocument -FilePath $fullPath
    
    # Add title
    Add-WordText -WordDocument $WordDocument -Text "Parallels RAS Configuration Documentation" `
        -FontSize 18 -Bold $true -Color Blue -Alignment Center
    
    Add-WordText -WordDocument $WordDocument -Text "" # Empty line
    
    # Add metadata
    Add-WordText -WordDocument $WordDocument -Text "Generated: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')" -FontSize 11
    Add-WordText -WordDocument $WordDocument -Text "Generated by: $env:USERNAME" -FontSize 11
    Add-WordText -WordDocument $WordDocument -Text "Computer: $env:COMPUTERNAME" -FontSize 11
    Add-WordText -WordDocument $WordDocument -Text "" # Empty line
    
    Write-LogMessage "Word document created successfully"
} catch {
    Write-LogMessage "Error creating Word document: $_" "ERROR"
    exit 1
}

# Function to add section to document
function Add-Section {
    param(
        [string]$Title,
        [string]$Content
    )
    
    Add-WordText -WordDocument $WordDocument -Text $Title -FontSize 14 -Bold $true -Color DarkBlue
    Add-WordText -WordDocument $WordDocument -Text "" # Empty line
    
    if ($Content) {
        Add-WordText -WordDocument $WordDocument -Text $Content -FontSize 10 -FontFamily "Courier New"
    }
    
    Add-WordText -WordDocument $WordDocument -Text "" # Empty line
}

# Function to add table to document
function Add-Table {
    param(
        [array]$Data,
        [array]$Headers
    )
    
    if ($Data.Count -eq 0) {
        Add-WordText -WordDocument $WordDocument -Text "No data available" -FontSize 10 -Italic $true
        Add-WordText -WordDocument $WordDocument -Text "" # Empty line
        return
    }
    
    # Prepare table data
    $tableData = @()
    
    # Add headers
    $tableData += ,@($Headers)
    
    # Add data rows
    foreach ($item in $Data) {
        $row = @()
        foreach ($header in $Headers) {
            $value = if ($item.PSObject.Properties[$header]) {
                $item.PSObject.Properties[$header].Value
            } else {
                ""
            }
            $row += [string]$value
        }
        $tableData += ,$row
    }
    
    # Add table to document
    Add-WordTable -WordDocument $WordDocument -DataTable $tableData -Design LightGridAccent1 -AutoFit AutoFitContent
    
    Add-WordText -WordDocument $WordDocument -Text "" # Empty line
}

# Collect RAS Configuration Data
Write-LogMessage "Collecting RAS configuration data..."

# Site Information
Write-LogMessage "Collecting site information..."
try {
    $sites = Get-RASSite -ErrorAction SilentlyContinue
    if ($sites) {
        Add-Section -Title "Site Configuration" -Content ""
        $siteData = $sites | ConvertTo-HashtableArray
        $headers = ($sites[0].PSObject.Properties.Name | Where-Object { $_ -notlike "*Internal*" -and $_ -notlike "*PS*" } | Select-Object -First 10)
        Add-Table -Data $siteData -Headers $headers
    } else {
        Add-Section -Title "Site Configuration" -Content "No sites found or unable to retrieve site information."
    }
} catch {
    Add-Section -Title "Site Configuration" -Content "Error retrieving site information: $_"
    Write-LogMessage "Warning: Could not retrieve site information: $_" "WARNING"
}

# RDS Host Information
Write-LogMessage "Collecting RDS host information..."
try {
    $rdsHosts = Get-RASRDSHost -ErrorAction SilentlyContinue
    if ($rdsHosts) {
        Add-Section -Title "RDS Host Configuration" -Content ""
        $rdsHostData = $rdsHosts | ConvertTo-HashtableArray
        $headers = ($rdsHosts[0].PSObject.Properties.Name | Where-Object { $_ -notlike "*Internal*" -and $_ -notlike "*PS*" } | Select-Object -First 10)
        Add-Table -Data $rdsHostData -Headers $headers
    } else {
        Add-Section -Title "RDS Host Configuration" -Content "No RDS hosts found or unable to retrieve RDS host information."
    }
} catch {
    Add-Section -Title "RDS Host Configuration" -Content "Error retrieving RDS host information: $_"
    Write-LogMessage "Warning: Could not retrieve RDS host information: $_" "WARNING"
}

# VDI Host Information
Write-LogMessage "Collecting VDI host information..."
try {
    $vdiHosts = Get-RASVDIHost -ErrorAction SilentlyContinue
    if ($vdiHosts) {
        Add-Section -Title "VDI Host Configuration" -Content ""
        $vdiHostData = $vdiHosts | ConvertTo-HashtableArray
        $headers = ($vdiHosts[0].PSObject.Properties.Name | Where-Object { $_ -notlike "*Internal*" -and $_ -notlike "*PS*" } | Select-Object -First 10)
        Add-Table -Data $vdiHostData -Headers $headers
    } else {
        Add-Section -Title "VDI Host Configuration" -Content "No VDI hosts found or unable to retrieve VDI host information."
    }
} catch {
    Add-Section -Title "VDI Host Configuration" -Content "Error retrieving VDI host information: $_"
    Write-LogMessage "Warning: Could not retrieve VDI host information: $_" "WARNING"
}

# AVD Host Information
Write-LogMessage "Collecting AVD host information..."
try {
    $avdHosts = Get-RASAVDHost -ErrorAction SilentlyContinue
    if ($avdHosts) {
        Add-Section -Title "AVD Host Configuration" -Content ""
        $avdHostData = $avdHosts | ConvertTo-HashtableArray
        $headers = ($avdHosts[0].PSObject.Properties.Name | Where-Object { $_ -notlike "*Internal*" -and $_ -notlike "*PS*" } | Select-Object -First 10)
        Add-Table -Data $avdHostData -Headers $headers
    } else {
        Add-Section -Title "AVD Host Configuration" -Content "No AVD hosts found or unable to retrieve AVD host information."
    }
} catch {
    Add-Section -Title "AVD Host Configuration" -Content "Error retrieving AVD host information: $_"
    Write-LogMessage "Warning: Could not retrieve AVD host information: $_" "WARNING"
}

# RDS Host Pool Information
Write-LogMessage "Collecting RDS host pool information..."
try {
    $rdsHostPools = Get-RASRDSHostPool -ErrorAction SilentlyContinue
    if ($rdsHostPools) {
        Add-Section -Title "RDS Host Pool Configuration" -Content ""
        $rdsHostPoolData = $rdsHostPools | ConvertTo-HashtableArray
        $headers = ($rdsHostPools[0].PSObject.Properties.Name | Where-Object { $_ -notlike "*Internal*" -and $_ -notlike "*PS*" } | Select-Object -First 10)
        Add-Table -Data $rdsHostPoolData -Headers $headers
    } else {
        Add-Section -Title "RDS Host Pool Configuration" -Content "No RDS host pools found or unable to retrieve RDS host pool information."
    }
} catch {
    Add-Section -Title "RDS Host Pool Configuration" -Content "Error retrieving RDS host pool information: $_"
    Write-LogMessage "Warning: Could not retrieve RDS host pool information: $_" "WARNING"
}

# VDI Host Pool Information
Write-LogMessage "Collecting VDI host pool information..."
try {
    $vdiHostPools = Get-RASVDIHostPool -ErrorAction SilentlyContinue
    if ($vdiHostPools) {
        Add-Section -Title "VDI Host Pool Configuration" -Content ""
        $vdiHostPoolData = $vdiHostPools | ConvertTo-HashtableArray
        $headers = ($vdiHostPools[0].PSObject.Properties.Name | Where-Object { $_ -notlike "*Internal*" -and $_ -notlike "*PS*" } | Select-Object -First 10)
        Add-Table -Data $vdiHostPoolData -Headers $headers
    } else {
        Add-Section -Title "VDI Host Pool Configuration" -Content "No VDI host pools found or unable to retrieve VDI host pool information."
    }
} catch {
    Add-Section -Title "VDI Host Pool Configuration" -Content "Error retrieving VDI host pool information: $_"
    Write-LogMessage "Warning: Could not retrieve VDI host pool information: $_" "WARNING"
}

# AVD Host Pool Information
Write-LogMessage "Collecting AVD host pool information..."
try {
    $avdHostPools = Get-RASAVDHostPool -ErrorAction SilentlyContinue
    if ($avdHostPools) {
        Add-Section -Title "AVD Host Pool Configuration" -Content ""
        $avdHostPoolData = $avdHostPools | ConvertTo-HashtableArray
        $headers = ($avdHostPools[0].PSObject.Properties.Name | Where-Object { $_ -notlike "*Internal*" -and $_ -notlike "*PS*" } | Select-Object -First 10)
        Add-Table -Data $avdHostPoolData -Headers $headers
    } else {
        Add-Section -Title "AVD Host Pool Configuration" -Content "No AVD host pools found or unable to retrieve AVD host pool information."
    }
} catch {
    Add-Section -Title "AVD Host Pool Configuration" -Content "Error retrieving AVD host pool information: $_"
    Write-LogMessage "Warning: Could not retrieve AVD host pool information: $_" "WARNING"
}

# Published Items Information
Write-LogMessage "Collecting published items information..."
try {
    $pubItems = Get-RASPubItem -ErrorAction SilentlyContinue
    if ($pubItems) {
        Add-Section -Title "Published Items Configuration" -Content ""
        $pubItemData = $pubItems | ConvertTo-HashtableArray
        $headers = ($pubItems[0].PSObject.Properties.Name | Where-Object { $_ -notlike "*Internal*" -and $_ -notlike "*PS*" } | Select-Object -First 10)
        Add-Table -Data $pubItemData -Headers $headers
    } else {
        Add-Section -Title "Published Items Configuration" -Content "No published items found or unable to retrieve published items information."
    }
} catch {
    Add-Section -Title "Published Items Configuration" -Content "Error retrieving published items information: $_"
    Write-LogMessage "Warning: Could not retrieve published items information: $_" "WARNING"
}

# Gateway Information
Write-LogMessage "Collecting gateway information..."
try {
    $gateways = Get-RASGateway -ErrorAction SilentlyContinue
    if ($gateways) {
        Add-Section -Title "Gateway Configuration" -Content ""
        $gatewayData = $gateways | ConvertTo-HashtableArray
        $headers = ($gateways[0].PSObject.Properties.Name | Where-Object { $_ -notlike "*Internal*" -and $_ -notlike "*PS*" } | Select-Object -First 10)
        Add-Table -Data $gatewayData -Headers $headers
    } else {
        Add-Section -Title "Gateway Configuration" -Content "No gateways found or unable to retrieve gateway information."
    }
} catch {
    Add-Section -Title "Gateway Configuration" -Content "Error retrieving gateway information: $_"
    Write-LogMessage "Warning: Could not retrieve gateway information: $_" "WARNING"
}

# License Information
Write-LogMessage "Collecting license information..."
try {
    $licenseDetails = Get-RASLicenseDetails -ErrorAction SilentlyContinue
    if ($licenseDetails) {
        Add-Section -Title "License Configuration" -Content ""
        $licenseData = $licenseDetails | ConvertTo-HashtableArray
        $headers = ($licenseDetails[0].PSObject.Properties.Name | Where-Object { $_ -notlike "*Internal*" -and $_ -notlike "*PS*" } | Select-Object -First 10)
        Add-Table -Data $licenseData -Headers $headers
    } else {
        Add-Section -Title "License Configuration" -Content "No license information found or unable to retrieve license information."
    }
} catch {
    Add-Section -Title "License Configuration" -Content "Error retrieving license information: $_"
    Write-LogMessage "Warning: Could not retrieve license information: $_" "WARNING"
}

# RDS Session Information
Write-LogMessage "Collecting RDS session information..."
try {
    $rdsSessions = Get-RASRDSession -ErrorAction SilentlyContinue
    if ($rdsSessions) {
        Add-Section -Title "Active RDS Sessions" -Content ""
        $rdsSessionData = $rdsSessions | ConvertTo-HashtableArray
        $headers = ($rdsSessions[0].PSObject.Properties.Name | Where-Object { $_ -notlike "*Internal*" -and $_ -notlike "*PS*" } | Select-Object -First 10)
        Add-Table -Data $rdsSessionData -Headers $headers
    } else {
        Add-Section -Title "Active RDS Sessions" -Content "No active RDS sessions found."
    }
} catch {
    Add-Section -Title "Active RDS Sessions" -Content "Error retrieving RDS session information: $_"
    Write-LogMessage "Warning: Could not retrieve RDS session information: $_" "WARNING"
}

# Broker Information
Write-LogMessage "Collecting broker information..."
try {
    $brokers = Get-RASBroker -ErrorAction SilentlyContinue
    if ($brokers) {
        Add-Section -Title "Broker Configuration" -Content ""
        $brokerData = $brokers | ConvertTo-HashtableArray
        $headers = ($brokers[0].PSObject.Properties.Name | Where-Object { $_ -notlike "*Internal*" -and $_ -notlike "*PS*" } | Select-Object -First 10)
        Add-Table -Data $brokerData -Headers $headers
    }
} catch {
    Write-LogMessage "Warning: Could not retrieve broker information: $_" "WARNING"
}

# Detailed Configuration (as formatted text)
Write-LogMessage "Collecting detailed configuration..."

# Get all available RAS cmdlets and try to get detailed info
$rasCmdlets = Get-Command -Module rasadmin | Where-Object { $_.Name -like "Get-RAS*" }

foreach ($cmdlet in $rasCmdlets) {
    $cmdletName = $cmdlet.Name
    Write-LogMessage "Processing $cmdletName..."
    
    try {
        # Check if cmdlet has mandatory parameters that aren't provided
        $cmdletInfo = Get-Command $cmdletName
        $mandatoryParams = $cmdletInfo.Parameters.Values | Where-Object { $_.Attributes.Mandatory -eq $true -and $_.Name -notin @('Confirm', 'WhatIf') }
        
        # Skip cmdlets that require mandatory parameters (other than Confirm/WhatIf)
        if ($mandatoryParams.Count -gt 0) {
            Write-LogMessage "Skipping $cmdletName - requires mandatory parameters: $($mandatoryParams.Name -join ', ')" "WARNING"
            continue
        }
        
        # Suppress all prompts and use non-interactive mode
        # Redirect stdin to prevent any input prompts
        $results = $null
        try {
            # Use a try-catch to handle any prompts gracefully
            $results = & $cmdletName -ErrorAction SilentlyContinue -Confirm:$false -WhatIf:$false 2>&1 | 
                Where-Object { $_ -isnot [System.Management.Automation.ErrorRecord] }
        } catch {
            # If cmdlet prompts or errors, skip it
            Write-LogMessage "Skipping $cmdletName due to error: $_" "WARNING"
            continue
        }
        
        if ($results) {
            Add-Section -Title "$cmdletName - Detailed Information" -Content ""
            
            foreach ($result in $results) {
                Add-WordText -WordDocument $WordDocument -Text "Object: $($result.Name)" -FontSize 10 -Bold $true
                
                $properties = $result.PSObject.Properties | Where-Object { $_.Name -notlike "*Internal*" -and $_.Name -notlike "*PS*" }
                
                foreach ($prop in $properties) {
                    $value = $prop.Value
                    if ($value -is [array]) {
                        $value = ($value | Out-String).Trim()
                    } elseif ($value -is [hashtable] -or $value -is [PSCustomObject]) {
                        $value = ($value | ConvertTo-Json -Depth 3)
                    }
                    
                    Add-WordText -WordDocument $WordDocument -Text "  $($prop.Name): $value" -FontSize 9 -FontFamily "Courier New"
                }
                
                Add-WordText -WordDocument $WordDocument -Text "" # Empty line
            }
        }
    } catch {
        Write-LogMessage "Warning: Could not execute $cmdletName : $_" "WARNING"
    }
}

# Save and close document
Write-LogMessage "Saving document to: $fullPath"

try {
    Save-WordDocument -WordDocument $WordDocument
    Write-LogMessage "Document saved successfully!"
} catch {
    Write-LogMessage "Error saving document: $_" "ERROR"
    exit 1
}

Write-LogMessage "Documentation complete! File saved to: $fullPath"

