<#
.SYNOPSIS
    Documents all Parallels RAS installation settings to a Word document.

.DESCRIPTION
    This script collects all configuration settings from a Parallels RAS installation
    using the Parallels RAS PowerShell module and exports them to a Word document.

.PARAMETER OutputPath
    Path where the Word document will be saved. Defaults to current directory.

.PARAMETER DocumentName
    Name of the Word document (without extension). Defaults to "RAS-Settings-{timestamp}".

.EXAMPLE
    .\Export-RASSettings.ps1 -OutputPath "C:\Reports" -DocumentName "RAS-Configuration"

.NOTES
    Requires:
    - Parallels RAS PowerShell module
    - Microsoft Word installed (for COM automation)
    - Appropriate permissions to access RAS configuration
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory = $false)]
    [string]$OutputPath = (Get-Location).Path,
    
    [Parameter(Mandatory = $false)]
    [string]$DocumentName = "RAS-Settings-$(Get-Date -Format 'yyyyMMdd-HHmmss')"
)

# Error handling - use Continue to allow graceful handling of missing cmdlets
$ErrorActionPreference = "Continue"

# Helper function to convert objects to array of hashtables for table display
function ConvertTo-HashtableArray {
    param([Parameter(ValueFromPipeline)]$InputObject)
    
    begin { $array = @() }
    process {
        $hashtable = @{}
        foreach ($prop in $InputObject.PSObject.Properties) {
            $value = $prop.Value
            if ($value -is [array]) {
                $value = ($value -join ", ")
            } elseif ($null -eq $value) {
                $value = ""
            }
            $hashtable[$prop.Name] = [string]$value
        }
        $array += [PSCustomObject]$hashtable
    }
    end { return $array }
}

# Function to write log messages
function Write-LogMessage {
    param([string]$Message, [string]$Level = "INFO")
    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    Write-Host "[$timestamp] [$Level] $Message" -ForegroundColor $(if ($Level -eq "ERROR") { "Red" } elseif ($Level -eq "WARNING") { "Yellow" } else { "Green" })
}

# Check if Parallels RAS module is installed
Write-LogMessage "Checking for Parallels RAS PowerShell module..."
try {
    $rasModule = Get-Module -ListAvailable -Name "rasadmin" | Select-Object -First 1
    if (-not $rasModule) {
        throw "Parallels RAS PowerShell module not found. Please install it first."
    }
    Write-LogMessage "Found Parallels RAS module version $($rasModule.Version)"
    
    # Import the module
    Import-Module -Name "rasadmin" -ErrorAction Stop
    Write-LogMessage "Module imported successfully"
} catch {
    Write-LogMessage "Error loading Parallels RAS module: $_" "ERROR"
    exit 1
}

# Check if Word is available
Write-LogMessage "Checking for Microsoft Word..."
try {
    $word = New-Object -ComObject Word.Application -ErrorAction Stop
    $word.Visible = $false
    Write-LogMessage "Microsoft Word is available"
} catch {
    Write-LogMessage "Error: Microsoft Word is not installed or not available. $_" "ERROR"
    exit 1
}

# Create Word document
Write-LogMessage "Creating Word document..."
try {
    $doc = $word.Documents.Add()
    $selection = $word.Selection
    
    # Document properties
    $doc.BuiltInDocumentProperties("Title").Value = "Parallels RAS Configuration Documentation"
    $doc.BuiltInDocumentProperties("Author").Value = $env:USERNAME
    $doc.BuiltInDocumentProperties("Comments").Value = "Generated on $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
    
    # Title
    $selection.Font.Size = 18
    $selection.Font.Bold = $true
    $selection.TypeText("Parallels RAS Configuration Documentation")
    $selection.TypeParagraph()
    $selection.TypeParagraph()
    
    # Date and time
    $selection.Font.Size = 11
    $selection.Font.Bold = $false
    $selection.TypeText("Generated: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')")
    $selection.TypeParagraph()
    $selection.TypeText("Generated by: $env:USERNAME")
    $selection.TypeParagraph()
    $selection.TypeText("Computer: $env:COMPUTERNAME")
    $selection.TypeParagraph()
    $selection.TypeParagraph()
    
    Write-LogMessage "Word document created successfully"
} catch {
    Write-LogMessage "Error creating Word document: $_" "ERROR"
    $word.Quit()
    exit 1
}

# Function to add section to document
function Add-Section {
    param(
        [string]$Title,
        [string]$Content
    )
    
    $selection.Font.Size = 14
    $selection.Font.Bold = $true
    $selection.TypeText($Title)
    $selection.TypeParagraph()
    $selection.TypeParagraph()
    
    $selection.Font.Size = 10
    $selection.Font.Bold = $false
    $selection.Font.Name = "Courier New"
    
    if ($Content) {
        $selection.TypeText($Content)
    }
    
    $selection.TypeParagraph()
    $selection.TypeParagraph()
}

# Function to add table to document
function Add-Table {
    param(
        [array]$Data,
        [array]$Headers
    )
    
    if ($Data.Count -eq 0) {
        $selection.TypeText("No data available")
        $selection.TypeParagraph()
        return
    }
    
    $selection.Font.Name = "Calibri"
    $selection.Font.Size = 10
    
    # Create table
    $table = $doc.Tables.Add($selection.Range, $Data.Count + 1, $Headers.Count)
    $table.Style = "Grid Table 4 - Accent 1"
    
    # Add headers
    for ($i = 0; $i -lt $Headers.Count; $i++) {
        $table.Cell(1, $i + 1).Range.Text = $Headers[$i]
        $table.Cell(1, $i + 1).Range.Font.Bold = $true
    }
    
    # Add data
    $row = 2
    foreach ($item in $Data) {
        for ($col = 0; $col -lt $Headers.Count; $col++) {
            $value = if ($item.PSObject.Properties[$Headers[$col]]) {
                $item.PSObject.Properties[$Headers[$col]].Value
            } else {
                ""
            }
            $table.Cell($row, $col + 1).Range.Text = [string]$value
        }
        $row++
    }
    
    $selection.EndKey(6) # Move to end of document
    $selection.TypeParagraph()
    $selection.TypeParagraph()
}

# Collect RAS Configuration Data
Write-LogMessage "Collecting RAS configuration data..."

# Site Information
Write-LogMessage "Collecting site information..."
try {
    $sites = Get-RASSite -ErrorAction SilentlyContinue
    if ($sites) {
        Add-Section -Title "Site Configuration" -Content ""
        $siteData = $sites | Select-Object Name, Description, SiteID, State, Version | ConvertTo-HashtableArray
        Add-Table -Data $siteData -Headers @("Name", "Description", "SiteID", "State", "Version")
    } else {
        Add-Section -Title "Site Configuration" -Content "No sites found or unable to retrieve site information."
    }
} catch {
    Add-Section -Title "Site Configuration" -Content "Error retrieving site information: $_"
    Write-LogMessage "Warning: Could not retrieve site information: $_" "WARNING"
}

# RDS Host Information
Write-LogMessage "Collecting RDS host information..."
try {
    $rdsHosts = Get-RASRDSHost -ErrorAction SilentlyContinue
    if ($rdsHosts) {
        Add-Section -Title "RDS Host Configuration" -Content ""
        $rdsHostData = $rdsHosts | ConvertTo-HashtableArray
        $headers = ($rdsHosts[0].PSObject.Properties.Name | Where-Object { $_ -notlike "*Internal*" -and $_ -notlike "*PS*" } | Select-Object -First 10)
        Add-Table -Data $rdsHostData -Headers $headers
    } else {
        Add-Section -Title "RDS Host Configuration" -Content "No RDS hosts found or unable to retrieve RDS host information."
    }
} catch {
    Add-Section -Title "RDS Host Configuration" -Content "Error retrieving RDS host information: $_"
    Write-LogMessage "Warning: Could not retrieve RDS host information: $_" "WARNING"
}

# VDI Host Information
Write-LogMessage "Collecting VDI host information..."
try {
    $vdiHosts = Get-RASVDIHost -ErrorAction SilentlyContinue
    if ($vdiHosts) {
        Add-Section -Title "VDI Host Configuration" -Content ""
        $vdiHostData = $vdiHosts | ConvertTo-HashtableArray
        $headers = ($vdiHosts[0].PSObject.Properties.Name | Where-Object { $_ -notlike "*Internal*" -and $_ -notlike "*PS*" } | Select-Object -First 10)
        Add-Table -Data $vdiHostData -Headers $headers
    } else {
        Add-Section -Title "VDI Host Configuration" -Content "No VDI hosts found or unable to retrieve VDI host information."
    }
} catch {
    Add-Section -Title "VDI Host Configuration" -Content "Error retrieving VDI host information: $_"
    Write-LogMessage "Warning: Could not retrieve VDI host information: $_" "WARNING"
}

# AVD Host Information
Write-LogMessage "Collecting AVD host information..."
try {
    $avdHosts = Get-RASAVDHost -ErrorAction SilentlyContinue
    if ($avdHosts) {
        Add-Section -Title "AVD Host Configuration" -Content ""
        $avdHostData = $avdHosts | ConvertTo-HashtableArray
        $headers = ($avdHosts[0].PSObject.Properties.Name | Where-Object { $_ -notlike "*Internal*" -and $_ -notlike "*PS*" } | Select-Object -First 10)
        Add-Table -Data $avdHostData -Headers $headers
    } else {
        Add-Section -Title "AVD Host Configuration" -Content "No AVD hosts found or unable to retrieve AVD host information."
    }
} catch {
    Add-Section -Title "AVD Host Configuration" -Content "Error retrieving AVD host information: $_"
    Write-LogMessage "Warning: Could not retrieve AVD host information: $_" "WARNING"
}

# RDS Host Pool Information
Write-LogMessage "Collecting RDS host pool information..."
try {
    $rdsHostPools = Get-RASRDSHostPool -ErrorAction SilentlyContinue
    if ($rdsHostPools) {
        Add-Section -Title "RDS Host Pool Configuration" -Content ""
        $rdsHostPoolData = $rdsHostPools | ConvertTo-HashtableArray
        $headers = ($rdsHostPools[0].PSObject.Properties.Name | Where-Object { $_ -notlike "*Internal*" -and $_ -notlike "*PS*" } | Select-Object -First 10)
        Add-Table -Data $rdsHostPoolData -Headers $headers
    } else {
        Add-Section -Title "RDS Host Pool Configuration" -Content "No RDS host pools found or unable to retrieve RDS host pool information."
    }
} catch {
    Add-Section -Title "RDS Host Pool Configuration" -Content "Error retrieving RDS host pool information: $_"
    Write-LogMessage "Warning: Could not retrieve RDS host pool information: $_" "WARNING"
}

# VDI Host Pool Information
Write-LogMessage "Collecting VDI host pool information..."
try {
    $vdiHostPools = Get-RASVDIHostPool -ErrorAction SilentlyContinue
    if ($vdiHostPools) {
        Add-Section -Title "VDI Host Pool Configuration" -Content ""
        $vdiHostPoolData = $vdiHostPools | ConvertTo-HashtableArray
        $headers = ($vdiHostPools[0].PSObject.Properties.Name | Where-Object { $_ -notlike "*Internal*" -and $_ -notlike "*PS*" } | Select-Object -First 10)
        Add-Table -Data $vdiHostPoolData -Headers $headers
    } else {
        Add-Section -Title "VDI Host Pool Configuration" -Content "No VDI host pools found or unable to retrieve VDI host pool information."
    }
} catch {
    Add-Section -Title "VDI Host Pool Configuration" -Content "Error retrieving VDI host pool information: $_"
    Write-LogMessage "Warning: Could not retrieve VDI host pool information: $_" "WARNING"
}

# AVD Host Pool Information
Write-LogMessage "Collecting AVD host pool information..."
try {
    $avdHostPools = Get-RASAVDHostPool -ErrorAction SilentlyContinue
    if ($avdHostPools) {
        Add-Section -Title "AVD Host Pool Configuration" -Content ""
        $avdHostPoolData = $avdHostPools | ConvertTo-HashtableArray
        $headers = ($avdHostPools[0].PSObject.Properties.Name | Where-Object { $_ -notlike "*Internal*" -and $_ -notlike "*PS*" } | Select-Object -First 10)
        Add-Table -Data $avdHostPoolData -Headers $headers
    } else {
        Add-Section -Title "AVD Host Pool Configuration" -Content "No AVD host pools found or unable to retrieve AVD host pool information."
    }
} catch {
    Add-Section -Title "AVD Host Pool Configuration" -Content "Error retrieving AVD host pool information: $_"
    Write-LogMessage "Warning: Could not retrieve AVD host pool information: $_" "WARNING"
}

# Published Items Information (Applications and Desktops)
Write-LogMessage "Collecting published items information..."
try {
    $pubItems = Get-RASPubItem -ErrorAction SilentlyContinue
    if ($pubItems) {
        Add-Section -Title "Published Items Configuration" -Content ""
        $pubItemData = $pubItems | ConvertTo-HashtableArray
        $headers = ($pubItems[0].PSObject.Properties.Name | Where-Object { $_ -notlike "*Internal*" -and $_ -notlike "*PS*" } | Select-Object -First 10)
        Add-Table -Data $pubItemData -Headers $headers
    } else {
        Add-Section -Title "Published Items Configuration" -Content "No published items found or unable to retrieve published items information."
    }
} catch {
    Add-Section -Title "Published Items Configuration" -Content "Error retrieving published items information: $_"
    Write-LogMessage "Warning: Could not retrieve published items information: $_" "WARNING"
}

# RDS Published Applications
Write-LogMessage "Collecting RDS published applications..."
try {
    $rdsApps = Get-RASPubRDSApp -ErrorAction SilentlyContinue
    if ($rdsApps) {
        Add-Section -Title "RDS Published Applications" -Content ""
        $rdsAppData = $rdsApps | ConvertTo-HashtableArray
        $headers = ($rdsApps[0].PSObject.Properties.Name | Where-Object { $_ -notlike "*Internal*" -and $_ -notlike "*PS*" } | Select-Object -First 10)
        Add-Table -Data $rdsAppData -Headers $headers
    }
} catch {
    Write-LogMessage "Warning: Could not retrieve RDS published applications: $_" "WARNING"
}

# VDI Published Applications
Write-LogMessage "Collecting VDI published applications..."
try {
    $vdiApps = Get-RASPubVDIApp -ErrorAction SilentlyContinue
    if ($vdiApps) {
        Add-Section -Title "VDI Published Applications" -Content ""
        $vdiAppData = $vdiApps | ConvertTo-HashtableArray
        $headers = ($vdiApps[0].PSObject.Properties.Name | Where-Object { $_ -notlike "*Internal*" -and $_ -notlike "*PS*" } | Select-Object -First 10)
        Add-Table -Data $vdiAppData -Headers $headers
    }
} catch {
    Write-LogMessage "Warning: Could not retrieve VDI published applications: $_" "WARNING"
}

# AVD Published Applications
Write-LogMessage "Collecting AVD published applications..."
try {
    $avdApps = Get-RASPubAVDApp -ErrorAction SilentlyContinue
    if ($avdApps) {
        Add-Section -Title "AVD Published Applications" -Content ""
        $avdAppData = $avdApps | ConvertTo-HashtableArray
        $headers = ($avdApps[0].PSObject.Properties.Name | Where-Object { $_ -notlike "*Internal*" -and $_ -notlike "*PS*" } | Select-Object -First 10)
        Add-Table -Data $avdAppData -Headers $headers
    }
} catch {
    Write-LogMessage "Warning: Could not retrieve AVD published applications: $_" "WARNING"
}

# Published Desktops
Write-LogMessage "Collecting published desktops..."
try {
    $rdsDesktops = Get-RASPubRDSDesktop -ErrorAction SilentlyContinue
    $vdiDesktops = Get-RASPubVDIDesktop -ErrorAction SilentlyContinue
    $avdDesktops = Get-RASPubAVDDesktop -ErrorAction SilentlyContinue
    
    if ($rdsDesktops) {
        Add-Section -Title "RDS Published Desktops" -Content ""
        $rdsDesktopData = $rdsDesktops | ConvertTo-HashtableArray
        $headers = ($rdsDesktops[0].PSObject.Properties.Name | Where-Object { $_ -notlike "*Internal*" -and $_ -notlike "*PS*" } | Select-Object -First 10)
        Add-Table -Data $rdsDesktopData -Headers $headers
    }
    if ($vdiDesktops) {
        Add-Section -Title "VDI Published Desktops" -Content ""
        $vdiDesktopData = $vdiDesktops | ConvertTo-HashtableArray
        $headers = ($vdiDesktops[0].PSObject.Properties.Name | Where-Object { $_ -notlike "*Internal*" -and $_ -notlike "*PS*" } | Select-Object -First 10)
        Add-Table -Data $vdiDesktopData -Headers $headers
    }
    if ($avdDesktops) {
        Add-Section -Title "AVD Published Desktops" -Content ""
        $avdDesktopData = $avdDesktops | ConvertTo-HashtableArray
        $headers = ($avdDesktops[0].PSObject.Properties.Name | Where-Object { $_ -notlike "*Internal*" -and $_ -notlike "*PS*" } | Select-Object -First 10)
        Add-Table -Data $avdDesktopData -Headers $headers
    }
} catch {
    Write-LogMessage "Warning: Could not retrieve published desktops: $_" "WARNING"
}

# Note: User information is typically managed through Active Directory integration
# Use Get-RASADIntegrationSettings to view AD integration configuration
Write-LogMessage "Collecting AD integration settings..."
try {
    $adSettings = Get-RASADIntegrationSettings -ErrorAction SilentlyContinue
    if ($adSettings) {
        Add-Section -Title "Active Directory Integration Settings" -Content ""
        $adSettingsData = $adSettings | ConvertTo-HashtableArray
        $headers = ($adSettings[0].PSObject.Properties.Name | Where-Object { $_ -notlike "*Internal*" -and $_ -notlike "*PS*" } | Select-Object -First 10)
        Add-Table -Data $adSettingsData -Headers $headers
    }
} catch {
    Write-LogMessage "Warning: Could not retrieve AD integration settings: $_" "WARNING"
}

# Gateway Information
Write-LogMessage "Collecting gateway information..."
try {
    $gateways = Get-RASGateway -ErrorAction SilentlyContinue
    if ($gateways) {
        Add-Section -Title "Gateway Configuration" -Content ""
        $gatewayData = $gateways | Select-Object Name, State, IPAddress, Port, Version | ConvertTo-HashtableArray
        Add-Table -Data $gatewayData -Headers @("Name", "State", "IPAddress", "Port", "Version")
    } else {
        Add-Section -Title "Gateway Configuration" -Content "No gateways found or unable to retrieve gateway information."
    }
} catch {
    Add-Section -Title "Gateway Configuration" -Content "Error retrieving gateway information: $_"
    Write-LogMessage "Warning: Could not retrieve gateway information: $_" "WARNING"
}

# License Information
Write-LogMessage "Collecting license information..."
try {
    $licenseDetails = Get-RASLicenseDetails -ErrorAction SilentlyContinue
    if ($licenseDetails) {
        Add-Section -Title "License Configuration" -Content ""
        $licenseData = $licenseDetails | ConvertTo-HashtableArray
        $headers = ($licenseDetails[0].PSObject.Properties.Name | Where-Object { $_ -notlike "*Internal*" -and $_ -notlike "*PS*" } | Select-Object -First 10)
        Add-Table -Data $licenseData -Headers $headers
    } else {
        Add-Section -Title "License Configuration" -Content "No license information found or unable to retrieve license information."
    }
} catch {
    Add-Section -Title "License Configuration" -Content "Error retrieving license information: $_"
    Write-LogMessage "Warning: Could not retrieve license information: $_" "WARNING"
}

# RDS Session Information
Write-LogMessage "Collecting RDS session information..."
try {
    $rdsSessions = Get-RASRDSession -ErrorAction SilentlyContinue
    if ($rdsSessions) {
        Add-Section -Title "Active RDS Sessions" -Content ""
        $rdsSessionData = $rdsSessions | ConvertTo-HashtableArray
        $headers = ($rdsSessions[0].PSObject.Properties.Name | Where-Object { $_ -notlike "*Internal*" -and $_ -notlike "*PS*" } | Select-Object -First 10)
        Add-Table -Data $rdsSessionData -Headers $headers
    } else {
        Add-Section -Title "Active RDS Sessions" -Content "No active RDS sessions found."
    }
} catch {
    Add-Section -Title "Active RDS Sessions" -Content "Error retrieving RDS session information: $_"
    Write-LogMessage "Warning: Could not retrieve RDS session information: $_" "WARNING"
}

# Broker Information
Write-LogMessage "Collecting broker information..."
try {
    $brokers = Get-RASBroker -ErrorAction SilentlyContinue
    if ($brokers) {
        Add-Section -Title "Broker Configuration" -Content ""
        $brokerData = $brokers | ConvertTo-HashtableArray
        $headers = ($brokers[0].PSObject.Properties.Name | Where-Object { $_ -notlike "*Internal*" -and $_ -notlike "*PS*" } | Select-Object -First 10)
        Add-Table -Data $brokerData -Headers $headers
    }
} catch {
    Write-LogMessage "Warning: Could not retrieve broker information: $_" "WARNING"
}

# Provider Information
Write-LogMessage "Collecting provider information..."
try {
    $providers = Get-RASProvider -ErrorAction SilentlyContinue
    if ($providers) {
        Add-Section -Title "Provider Configuration" -Content ""
        $providerData = $providers | ConvertTo-HashtableArray
        $headers = ($providers[0].PSObject.Properties.Name | Where-Object { $_ -notlike "*Internal*" -and $_ -notlike "*PS*" } | Select-Object -First 10)
        Add-Table -Data $providerData -Headers $headers
    }
} catch {
    Write-LogMessage "Warning: Could not retrieve provider information: $_" "WARNING"
}

# Theme Information
Write-LogMessage "Collecting theme information..."
try {
    $themes = Get-RASTheme -ErrorAction SilentlyContinue
    if ($themes) {
        Add-Section -Title "Theme Configuration" -Content ""
        $themeData = $themes | ConvertTo-HashtableArray
        $headers = ($themes[0].PSObject.Properties.Name | Where-Object { $_ -notlike "*Internal*" -and $_ -notlike "*PS*" } | Select-Object -First 10)
        Add-Table -Data $themeData -Headers $headers
    }
} catch {
    Write-LogMessage "Warning: Could not retrieve theme information: $_" "WARNING"
}

# Client Policy Information
Write-LogMessage "Collecting client policy information..."
try {
    $clientPolicies = Get-RASClientPolicy -ErrorAction SilentlyContinue
    if ($clientPolicies) {
        Add-Section -Title "Client Policy Configuration" -Content ""
        $clientPolicyData = $clientPolicies | ConvertTo-HashtableArray
        $headers = ($clientPolicies[0].PSObject.Properties.Name | Where-Object { $_ -notlike "*Internal*" -and $_ -notlike "*PS*" } | Select-Object -First 10)
        Add-Table -Data $clientPolicyData -Headers $headers
    }
} catch {
    Write-LogMessage "Warning: Could not retrieve client policy information: $_" "WARNING"
}

# System Settings
Write-LogMessage "Collecting system settings..."
try {
    $systemSettings = Get-RASSystemSettings -ErrorAction SilentlyContinue
    if ($systemSettings) {
        Add-Section -Title "System Settings" -Content ""
        $systemSettingsData = $systemSettings | ConvertTo-HashtableArray
        $headers = ($systemSettings[0].PSObject.Properties.Name | Where-Object { $_ -notlike "*Internal*" -and $_ -notlike "*PS*" } | Select-Object -First 10)
        Add-Table -Data $systemSettingsData -Headers $headers
    }
} catch {
    Write-LogMessage "Warning: Could not retrieve system settings: $_" "WARNING"
}

# Detailed Configuration (as formatted text)
Write-LogMessage "Collecting detailed configuration..."
$selection.Font.Name = "Calibri"
$selection.Font.Size = 10

# Get all available RAS cmdlets and try to get detailed info
$rasCmdlets = Get-Command -Module rasadmin | Where-Object { $_.Name -like "Get-RAS*" }

foreach ($cmdlet in $rasCmdlets) {
    $cmdletName = $cmdlet.Name
    Write-LogMessage "Processing $cmdletName..."
    
    try {
        $results = & $cmdletName -ErrorAction SilentlyContinue
        
        if ($results) {
            Add-Section -Title "$cmdletName - Detailed Information" -Content ""
            
            foreach ($result in $results) {
                $selection.Font.Bold = $true
                $selection.TypeText("Object: $($result.Name)")
                $selection.Font.Bold = $false
                $selection.TypeParagraph()
                
                $properties = $result.PSObject.Properties | Where-Object { $_.Name -notlike "*Internal*" -and $_.Name -notlike "*PS*" }
                
                foreach ($prop in $properties) {
                    $value = $prop.Value
                    if ($value -is [array]) {
                        $value = ($value | Out-String).Trim()
                    } elseif ($value -is [hashtable] -or $value -is [PSCustomObject]) {
                        $value = ($value | ConvertTo-Json -Depth 3)
                    }
                    
                    $selection.TypeText("  $($prop.Name): $value")
                    $selection.TypeParagraph()
                }
                
                $selection.TypeParagraph()
            }
        }
    } catch {
        Write-LogMessage "Warning: Could not execute $cmdletName : $_" "WARNING"
    }
}

# Ensure output directory exists
if (-not (Test-Path $OutputPath)) {
    Write-LogMessage "Creating output directory: $OutputPath"
    try {
        New-Item -ItemType Directory -Path $OutputPath -Force | Out-Null
    } catch {
        Write-LogMessage "Error creating output directory: $_" "ERROR"
        $word.Quit()
        exit 1
    }
}

# Save document
$fullPath = Join-Path $OutputPath "$DocumentName.docx"
Write-LogMessage "Saving document to: $fullPath"

try {
    $doc.SaveAs([ref]$fullPath)
    Write-LogMessage "Document saved successfully!"
} catch {
    Write-LogMessage "Error saving document: $_" "ERROR"
    $word.Quit()
    exit 1
}

# Close Word
$doc.Close()
$word.Quit()

# Release COM objects
[System.Runtime.Interopservices.Marshal]::ReleaseComObject($doc) | Out-Null
[System.Runtime.Interopservices.Marshal]::ReleaseComObject($word) | Out-Null
[System.GC]::Collect()
[System.GC]::WaitForPendingFinalizers()

Write-LogMessage "Documentation complete! File saved to: $fullPath"

