<#
.SYNOPSIS
    Documents all Parallels RAS installation settings to a Word document.

.DESCRIPTION
    This script collects all configuration settings from a Parallels RAS installation
    using the Parallels RAS PowerShell module and exports them to a Word document.

.PARAMETER OutputPath
    Path where the Word document will be saved. Defaults to current directory.

.PARAMETER DocumentName
    Name of the Word document (without extension). Defaults to "RAS-Settings-{timestamp}".

.EXAMPLE
    .\Export-RASSettings.ps1 -OutputPath "C:\Reports" -DocumentName "RAS-Configuration"

.NOTES
    Requires:
    - Parallels RAS PowerShell module
    - Microsoft Word installed (for COM automation)
    - Appropriate permissions to access RAS configuration
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory = $false)]
    [string]$OutputPath = (Get-Location).Path,
    
    [Parameter(Mandatory = $false)]
    [string]$DocumentName = "RAS-Settings-$(Get-Date -Format 'yyyyMMdd-HHmmss')"
)

# Error handling - use Continue to allow graceful handling of missing cmdlets
$ErrorActionPreference = "Continue"

# Helper function to convert objects to array of hashtables for table display
function ConvertTo-HashtableArray {
    param([Parameter(ValueFromPipeline)]$InputObject)
    
    begin { $array = @() }
    process {
        $hashtable = @{}
        foreach ($prop in $InputObject.PSObject.Properties) {
            $value = $prop.Value
            if ($value -is [array]) {
                $value = ($value -join ", ")
            } elseif ($null -eq $value) {
                $value = ""
            }
            $hashtable[$prop.Name] = [string]$value
        }
        $array += [PSCustomObject]$hashtable
    }
    end { return $array }
}

# Function to write log messages
function Write-LogMessage {
    param([string]$Message, [string]$Level = "INFO")
    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    Write-Host "[$timestamp] [$Level] $Message" -ForegroundColor $(if ($Level -eq "ERROR") { "Red" } elseif ($Level -eq "WARNING") { "Yellow" } else { "Green" })
}

# Check if Parallels RAS module is installed
Write-LogMessage "Checking for Parallels RAS PowerShell module..."
try {
    $rasModule = Get-Module -ListAvailable -Name "ParallelsRAS" | Select-Object -First 1
    if (-not $rasModule) {
        throw "Parallels RAS PowerShell module not found. Please install it first."
    }
    Write-LogMessage "Found Parallels RAS module version $($rasModule.Version)"
    
    # Import the module
    Import-Module -Name "ParallelsRAS" -ErrorAction Stop
    Write-LogMessage "Module imported successfully"
} catch {
    Write-LogMessage "Error loading Parallels RAS module: $_" "ERROR"
    exit 1
}

# Check if Word is available
Write-LogMessage "Checking for Microsoft Word..."
try {
    $word = New-Object -ComObject Word.Application -ErrorAction Stop
    $word.Visible = $false
    Write-LogMessage "Microsoft Word is available"
} catch {
    Write-LogMessage "Error: Microsoft Word is not installed or not available. $_" "ERROR"
    exit 1
}

# Create Word document
Write-LogMessage "Creating Word document..."
try {
    $doc = $word.Documents.Add()
    $selection = $word.Selection
    
    # Document properties
    $doc.BuiltInDocumentProperties("Title").Value = "Parallels RAS Configuration Documentation"
    $doc.BuiltInDocumentProperties("Author").Value = $env:USERNAME
    $doc.BuiltInDocumentProperties("Comments").Value = "Generated on $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
    
    # Title
    $selection.Font.Size = 18
    $selection.Font.Bold = $true
    $selection.TypeText("Parallels RAS Configuration Documentation")
    $selection.TypeParagraph()
    $selection.TypeParagraph()
    
    # Date and time
    $selection.Font.Size = 11
    $selection.Font.Bold = $false
    $selection.TypeText("Generated: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')")
    $selection.TypeParagraph()
    $selection.TypeText("Generated by: $env:USERNAME")
    $selection.TypeParagraph()
    $selection.TypeText("Computer: $env:COMPUTERNAME")
    $selection.TypeParagraph()
    $selection.TypeParagraph()
    
    Write-LogMessage "Word document created successfully"
} catch {
    Write-LogMessage "Error creating Word document: $_" "ERROR"
    $word.Quit()
    exit 1
}

# Function to add section to document
function Add-Section {
    param(
        [string]$Title,
        [string]$Content
    )
    
    $selection.Font.Size = 14
    $selection.Font.Bold = $true
    $selection.TypeText($Title)
    $selection.TypeParagraph()
    $selection.TypeParagraph()
    
    $selection.Font.Size = 10
    $selection.Font.Bold = $false
    $selection.Font.Name = "Courier New"
    
    if ($Content) {
        $selection.TypeText($Content)
    }
    
    $selection.TypeParagraph()
    $selection.TypeParagraph()
}

# Function to add table to document
function Add-Table {
    param(
        [array]$Data,
        [array]$Headers
    )
    
    if ($Data.Count -eq 0) {
        $selection.TypeText("No data available")
        $selection.TypeParagraph()
        return
    }
    
    $selection.Font.Name = "Calibri"
    $selection.Font.Size = 10
    
    # Create table
    $table = $doc.Tables.Add($selection.Range, $Data.Count + 1, $Headers.Count)
    $table.Style = "Grid Table 4 - Accent 1"
    
    # Add headers
    for ($i = 0; $i -lt $Headers.Count; $i++) {
        $table.Cell(1, $i + 1).Range.Text = $Headers[$i]
        $table.Cell(1, $i + 1).Range.Font.Bold = $true
    }
    
    # Add data
    $row = 2
    foreach ($item in $Data) {
        for ($col = 0; $col -lt $Headers.Count; $col++) {
            $value = if ($item.PSObject.Properties[$Headers[$col]]) {
                $item.PSObject.Properties[$Headers[$col]].Value
            } else {
                ""
            }
            $table.Cell($row, $col + 1).Range.Text = [string]$value
        }
        $row++
    }
    
    $selection.EndKey(6) # Move to end of document
    $selection.TypeParagraph()
    $selection.TypeParagraph()
}

# Collect RAS Configuration Data
Write-LogMessage "Collecting RAS configuration data..."

# Site Information
Write-LogMessage "Collecting site information..."
try {
    $sites = Get-RASSite -ErrorAction SilentlyContinue
    if ($sites) {
        Add-Section -Title "Site Configuration" -Content ""
        $siteData = $sites | Select-Object Name, Description, SiteID, State, Version | ConvertTo-HashtableArray
        Add-Table -Data $siteData -Headers @("Name", "Description", "SiteID", "State", "Version")
    } else {
        Add-Section -Title "Site Configuration" -Content "No sites found or unable to retrieve site information."
    }
} catch {
    Add-Section -Title "Site Configuration" -Content "Error retrieving site information: $_"
    Write-LogMessage "Warning: Could not retrieve site information: $_" "WARNING"
}

# Server Information
Write-LogMessage "Collecting server information..."
try {
    $servers = Get-RASServer -ErrorAction SilentlyContinue
    if ($servers) {
        Add-Section -Title "Server Configuration" -Content ""
        $serverData = $servers | Select-Object Name, ServerType, State, IPAddress, Version, OSVersion | ConvertTo-HashtableArray
        Add-Table -Data $serverData -Headers @("Name", "ServerType", "State", "IPAddress", "Version", "OSVersion")
    } else {
        Add-Section -Title "Server Configuration" -Content "No servers found or unable to retrieve server information."
    }
} catch {
    Add-Section -Title "Server Configuration" -Content "Error retrieving server information: $_"
    Write-LogMessage "Warning: Could not retrieve server information: $_" "WARNING"
}

# Farm Information
Write-LogMessage "Collecting farm information..."
try {
    $farms = Get-RASFarm -ErrorAction SilentlyContinue
    if ($farms) {
        Add-Section -Title "Farm Configuration" -Content ""
        $farmData = $farms | Select-Object Name, Description, FarmType, State, LoadBalancingMethod | ConvertTo-HashtableArray
        Add-Table -Data $farmData -Headers @("Name", "Description", "FarmType", "State", "LoadBalancingMethod")
    } else {
        Add-Section -Title "Farm Configuration" -Content "No farms found or unable to retrieve farm information."
    }
} catch {
    Add-Section -Title "Farm Configuration" -Content "Error retrieving farm information: $_"
    Write-LogMessage "Warning: Could not retrieve farm information: $_" "WARNING"
}

# Application Information
Write-LogMessage "Collecting application information..."
try {
    $applications = Get-RASApplication -ErrorAction SilentlyContinue
    if ($applications) {
        Add-Section -Title "Application Configuration" -Content ""
        $appData = $applications | Select-Object Name, DisplayName, ApplicationType, State, FarmName | ConvertTo-HashtableArray
        Add-Table -Data $appData -Headers @("Name", "DisplayName", "ApplicationType", "State", "FarmName")
    } else {
        Add-Section -Title "Application Configuration" -Content "No applications found or unable to retrieve application information."
    }
} catch {
    Add-Section -Title "Application Configuration" -Content "Error retrieving application information: $_"
    Write-LogMessage "Warning: Could not retrieve application information: $_" "WARNING"
}

# User Information
Write-LogMessage "Collecting user information..."
try {
    $users = Get-RASUser -ErrorAction SilentlyContinue
    if ($users) {
        Add-Section -Title "User Configuration" -Content ""
        $userData = $users | Select-Object UserName, DisplayName, Email, Enabled | ConvertTo-HashtableArray
        Add-Table -Data $userData -Headers @("UserName", "DisplayName", "Email", "Enabled")
    } else {
        Add-Section -Title "User Configuration" -Content "No users found or unable to retrieve user information."
    }
} catch {
    Add-Section -Title "User Configuration" -Content "Error retrieving user information: $_"
    Write-LogMessage "Warning: Could not retrieve user information: $_" "WARNING"
}

# Gateway Information
Write-LogMessage "Collecting gateway information..."
try {
    $gateways = Get-RASGateway -ErrorAction SilentlyContinue
    if ($gateways) {
        Add-Section -Title "Gateway Configuration" -Content ""
        $gatewayData = $gateways | Select-Object Name, State, IPAddress, Port, Version | ConvertTo-HashtableArray
        Add-Table -Data $gatewayData -Headers @("Name", "State", "IPAddress", "Port", "Version")
    } else {
        Add-Section -Title "Gateway Configuration" -Content "No gateways found or unable to retrieve gateway information."
    }
} catch {
    Add-Section -Title "Gateway Configuration" -Content "Error retrieving gateway information: $_"
    Write-LogMessage "Warning: Could not retrieve gateway information: $_" "WARNING"
}

# License Information
Write-LogMessage "Collecting license information..."
try {
    $licenses = Get-RASLicense -ErrorAction SilentlyContinue
    if ($licenses) {
        Add-Section -Title "License Configuration" -Content ""
        $licenseData = $licenses | Select-Object LicenseType, TotalLicenses, UsedLicenses, AvailableLicenses, ExpirationDate | ConvertTo-HashtableArray
        Add-Table -Data $licenseData -Headers @("LicenseType", "TotalLicenses", "UsedLicenses", "AvailableLicenses", "ExpirationDate")
    } else {
        Add-Section -Title "License Configuration" -Content "No license information found or unable to retrieve license information."
    }
} catch {
    Add-Section -Title "License Configuration" -Content "Error retrieving license information: $_"
    Write-LogMessage "Warning: Could not retrieve license information: $_" "WARNING"
}

# Session Information
Write-LogMessage "Collecting session information..."
try {
    $sessions = Get-RASSession -ErrorAction SilentlyContinue
    if ($sessions) {
        Add-Section -Title "Active Sessions" -Content ""
        $sessionData = $sessions | Select-Object UserName, ApplicationName, ServerName, State, StartTime | ConvertTo-HashtableArray
        Add-Table -Data $sessionData -Headers @("UserName", "ApplicationName", "ServerName", "State", "StartTime")
    } else {
        Add-Section -Title "Active Sessions" -Content "No active sessions found."
    }
} catch {
    Add-Section -Title "Active Sessions" -Content "Error retrieving session information: $_"
    Write-LogMessage "Warning: Could not retrieve session information: $_" "WARNING"
}

# Detailed Configuration (as formatted text)
Write-LogMessage "Collecting detailed configuration..."
$selection.Font.Name = "Calibri"
$selection.Font.Size = 10

# Get all available RAS cmdlets and try to get detailed info
$rasCmdlets = Get-Command -Module ParallelsRAS | Where-Object { $_.Name -like "Get-RAS*" }

foreach ($cmdlet in $rasCmdlets) {
    $cmdletName = $cmdlet.Name
    Write-LogMessage "Processing $cmdletName..."
    
    try {
        $results = & $cmdletName -ErrorAction SilentlyContinue
        
        if ($results) {
            Add-Section -Title "$cmdletName - Detailed Information" -Content ""
            
            foreach ($result in $results) {
                $selection.Font.Bold = $true
                $selection.TypeText("Object: $($result.Name)")
                $selection.Font.Bold = $false
                $selection.TypeParagraph()
                
                $properties = $result.PSObject.Properties | Where-Object { $_.Name -notlike "*Internal*" -and $_.Name -notlike "*PS*" }
                
                foreach ($prop in $properties) {
                    $value = $prop.Value
                    if ($value -is [array]) {
                        $value = ($value | Out-String).Trim()
                    } elseif ($value -is [hashtable] -or $value -is [PSCustomObject]) {
                        $value = ($value | ConvertTo-Json -Depth 3)
                    }
                    
                    $selection.TypeText("  $($prop.Name): $value")
                    $selection.TypeParagraph()
                }
                
                $selection.TypeParagraph()
            }
        }
    } catch {
        Write-LogMessage "Warning: Could not execute $cmdletName : $_" "WARNING"
    }
}

# Ensure output directory exists
if (-not (Test-Path $OutputPath)) {
    Write-LogMessage "Creating output directory: $OutputPath"
    try {
        New-Item -ItemType Directory -Path $OutputPath -Force | Out-Null
    } catch {
        Write-LogMessage "Error creating output directory: $_" "ERROR"
        $word.Quit()
        exit 1
    }
}

# Save document
$fullPath = Join-Path $OutputPath "$DocumentName.docx"
Write-LogMessage "Saving document to: $fullPath"

try {
    $doc.SaveAs([ref]$fullPath)
    Write-LogMessage "Document saved successfully!"
} catch {
    Write-LogMessage "Error saving document: $_" "ERROR"
    $word.Quit()
    exit 1
}

# Close Word
$doc.Close()
$word.Quit()

# Release COM objects
[System.Runtime.Interopservices.Marshal]::ReleaseComObject($doc) | Out-Null
[System.Runtime.Interopservices.Marshal]::ReleaseComObject($word) | Out-Null
[System.GC]::Collect()
[System.GC]::WaitForPendingFinalizers()

Write-LogMessage "Documentation complete! File saved to: $fullPath"

